name: Deploy Lambda

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_TO_ASSIGN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Package Lambda
        run: |
          mkdir -p package
          cp lambda_function.py package/
          cd package
          zip -r ../lambda.zip .

      - name: Deploy to AWS Lambda
        env:
          LAMBDA_FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_NAME }}
          TABLE_NAME: ${{ secrets.TABLE_NAME }}
          PARTITION_KEY: ${{ secrets.PARTITION_KEY }}
          PARTITION_VALUE: ${{ secrets.PARTITION_VALUE }}
        run: |
          aws lambda update-function-code \
            --function-name $LAMBDA_FUNCTION_NAME \
            --zip-file fileb://lambda.zip

          aws lambda update-function-configuration \
            --function-name $LAMBDA_FUNCTION_NAME \
            --environment "Variables={TABLE_NAME=$TABLE_NAME,PARTITION_KEY=$PARTITION_KEY,PARTITION_VALUE=$PARTITION_VALUE}"
